-- 1
SELECT * FROM EMPLOYEES
WHERE ADDRESS LIKE '%Elgin,IL%';

-- 2 
SELECT * FROM EMPLOYEES
WHERE B_DATE LIKE '%197%'; 

-- 3
SELECT * FROM EMPLOYEES 
WHERE DEP_ID = 5 AND (SALARY <= 70000 AND SALARY >= 60000);

-- 4A
SELECT * FROM EMPLOYEES 
ORDER BY DEP_ID;

-- 4B
SELECT * FROM EMPLOYEES
ORDER BY DEP_ID DESC, L_NAME DESC;

-- 5A
SELECT DEP_ID, COUNT(*) FROM EMPLOYEES
GROUP BY DEP_ID;

-- 5B
SELECT DEP_ID, COUNT(*), AVG(SALARY) FROM EMPLOYEES
GROUP BY DEP_ID;

-- 5C
SELECT DEP_ID, COUNT(*) AS "NUM_EMPLOYEES", AVG(SALARY) AS "AVG_SALARY" FROM EMPLOYEES
GROUP BY DEP_ID;

-- 5D
SELECT DEP_ID, COUNT(*) AS "NUM_EMPLOYEES", AVG(SALARY) AS "AVG_SALARY" FROM EMPLOYEES
GROUP BY DEP_ID
ORDER BY AVG_SALARY;

-- 5E
SELECT DEP_ID, COUNT(*) AS "NUM_EMPLOYEES", AVG(SALARY) AS "AVG_SALARY" FROM EMPLOYEES
GROUP BY DEP_ID
HAVING COUNT(*) < 4
ORDER BY AVG_SALARY;

-- 6
SELECT * FROM EMPLOYEES 
INNER JOIN DEPARTMENTS
ON EMPLOYEES.DEP_ID = DEPARTMENTS.DEPT_ID_DEP
ORDER BY DEP_NAME DESC, L_NAME DESC;
